# Backend settings

# Production address (Can be multiple if needed BackendAddress2, BackendAddress3, ...)
BackendAddress1 = https://comm.sqrll.net

# Actual domain used in production
Domain = .sqrll.net

# Same as Domain but for debug configuration (Overrides Domain) - Also adds BackendAddress to whitlelist
# 1. Remeber to add 
# 127.0.0.1    <DebugDomain>
# To hosts file (C:\Windows\System32\Drivers\etc\hosts)
# 2. And edit xampp\apache\conf\extra\httpd-vhosts.conf
DebugDomain = local.srvdebug.nonexistent

# Server port for HTTP/REST connections
Port = 8080

# Server port for web sockets
PortWS = 8081

# Decide if you want SSL enabled (Disable for local debug as SSL on localhost will fail by browser)
EnableSSL = false 
# Provide name if it's in Config dir with this file or full path
SSLKey = key.pem 
# Provide name if it's in Config dir with this file or full path
SSLCert = cert.pem

# Abuse protection settings
RateLimitNumberPerIP = 55
RateLimitTimeToClearInMins = 60
