# Backend settings

# Explicit listen host
SocketListenHost = 0.0.0.0

# Production address (Can be multiple if needed BackendAddress2, BackendAddress3, ...)
BackendAddress1 = https://comm.sqrll.net

# Actual domain used in production
Domain = .sqrll.net

# Same as Domain but for debug configuration (Overrides Domain) - Also adds BackendAddress to whitlelist
DebugDomain = localhost

# Server port for HTTP/REST connections
Port = 8080
# Server port for web sockets
PortWS = 8081

# Decide if you want SSL enabled (Disable for local debug as SSL on localhost will fail by browser)
EnableSSL = false
# Should paths assume file is in Assets/Config dir or absolute?
SSLPathsAbsolute = true
# Provide name if it's in Config dir with this file or full path
SSLKey = /etc/letsencrypt/live/comm.sqrll.net/privkey.pem
# Provide name if it's in Config dir with this file or full path
SSLCert = /etc/letsencrypt/live/comm.sqrll.net/fullchain.pem

# How long does user session live before ending (in seconds)
SessionLifeTime = 3000

# How long should we keep token for password reset alive (in mins)
PasswordResetTokenAliveTimeMins = 15

# Abuse protection settings
RateLimitNumberPerIP = 55
PasswordRateLimitNumberPerIP = 25
RateLimitTimeToClearInMins = 60
