# Server settings

# Server port for connections
Port = 8080

# Decide if you want SSL enabled
EnableSSL = true
# Provide name if it's in Config dir with this file or full path
SSLKey = key.pem 
# Provide name if it's in Config dir with this file or full path
SSLCert = cert.pem
