name: communicator
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:8080" # Backend rest
      - "8081:8081" # Backend socket

    network_mode: host

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 5s
      retries: 3

    restart: unless-stopped

  mediasoup:
    build: ./mediasoup

    ports:
      - "3000:3000" # mediasoup port
      - "40000-40100:40000-40100/udp"

    network_mode: host

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3

    restart: unless-stopped

  autoheal:
    image: willfarrell/autoheal
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

