name: communicator
services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile.release
      args:
        VERSION: ${BACKEND_VERSION:?Set BACKEND_VERSION in .env.backend}
    env_file:
      - .env.backend
      - .env.encryptionpass
      - .env.voice

    devices:
        - "/dev/urandom:/dev/urandom"

    volumes:
        # Persist the crashpad database across container restarts AND recreations
        # so a minidump written by a crash can still be uploaded on the next start.
        - sqrll_sentry:/app/.sentry-native

    ports:
      - "8080:8080" # Backend rest
      - "8081:8081" # Backend socket
    network_mode: host

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    labels:
      - "autoheal=true"
    restart: unless-stopped


  voice_service:
    build:
      context: ../services/SquirrelCommunicatorVoice
      dockerfile: Dockerfile
    env_file:
      - .env.voice
      - .env.image

    ports:
      - "8082:8082" # Voice port
    network_mode: host

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    labels:
      - "autoheal=true"
    restart: unless-stopped


  image_service:
    build:
      context: ../services/SquirrelCommunicatorImage
      dockerfile: Dockerfile
    env_file:
      - .env.image
    volumes:
      # Location of images on disk
      - ./sqrll_data/media:/var/data/sqrll/media
    ports:
      - "8083:8083" # Image port
    network_mode: host
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    labels:
      - "autoheal=true"
    restart: unless-stopped


  autoheal:
    image: willfarrell/autoheal
    restart: always
    environment:
      - AUTOHEAL_INTERVAL=5           # Check every 5 seconds
      - AUTOHEAL_START_PERIOD=30      # 30 seconds to start for each container
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


volumes:
  sqrll_sentry:
