name: Build Linux
on: [push, pull_request]
jobs:
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config: [Debug, Release]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
          
      - name: Download Submodules
        run: |
          echo "Using git submodule update"
          git submodule update --init --recursive
        shell: bash
      
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            ninja-build \
            libgl1-mesa-dev \
            libglu1-mesa-dev \
            libasound2-dev \
            libpulse-dev \
            libaudio-dev \
            libx11-dev \
            libxext-dev \
            libxrandr-dev \
            libxcursor-dev \
            libxfixes-dev \
            libxi-dev \
            libxinerama-dev \
            libxxf86vm-dev \
            libxss-dev \
            libfreetype6-dev \
            libharfbuzz-dev \
            libfontconfig1-dev \
            pkg-config
      
      - name: Configure and Build
        run: |
          echo "Configuring Linux ${{ matrix.config }} build..."
          mkdir -p build/linux-${{ matrix.config }}
          cd build/linux-${{ matrix.config }}
          
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.config }} \
                -G "Ninja" \
                ../../Project
          
          echo "Building Linux project..."
          cmake --build . --config ${{ matrix.config }} --parallel $(nproc)
        env:
          CI: true
      
      - name: Upload Linux Build
        uses: actions/upload-artifact@v4
        with:
          name: build-linux-${{ matrix.config }}
          path: |
            build/linux-${{ matrix.config }}/**
            !build/linux-${{ matrix.config }}/_deps